# Site
name: "Haritha Paul"
title: "Haritha Paul"
description: "Hi, I'm Haritha Paul. Welcome to my mindspace."
logo: 'assets/images/logotrans.png'
favicon: 'assets/images/logotrans.png'
baseurl: ''
google_analytics: 'UA-132574461-1'
disqus: 'haritha_paul'
mailchimp-list: 'https://github.us10.list-manage.com/subscribe/post?u=1697f0b5cd23b8e7c374b14a3&amp;id=2c3b883d09'
include: ["_pages"]
permalink: /:title/
email: harithapaul97@gmail.com

# Authors
authors:
  haritha:
    name: Haritha
    display_name: Haritha
    avatar: 'assets/images/avatar.png'
    #gravatar: e33d66d6ab7986c4cf6f4d4e40e76583
    email: harithapaul97@gmail.com
    web: 
    twitter: https://twitter.com/haritha_97
    description: "Software Engineer|Computer Science Undergrad|WeTech Qualcomm Global Scholar"
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
